{
 "title": "Lorona",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lorona_system_uptime" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lorona_system_cpu_usage", "legendFormat": "CPU Usage Percentage" }
   ]
  },
  {
   "title": "Endpoints Up?",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "targets": [
    { "expr": "lorona_endpoint_up" },
    { "expr": "lorona_endpoint_duration" }
   ]
  },
  {
   "title": "Backup Monitoring",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 7 },
   "targets": [
    { "expr": "lorona_backup_info" }
   ]
  },
  {
   "title": "Hard Drive Usage",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "lorona_hd_available" }
   ]
  },
  {
   "title": "StatusCodes from Logs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lorona_status_codes", "legendFormat": "{{status_code}}" }
   ]
  }
 ]
}