---
# Configuration file for Lorona - a very simple container monitoring solution

container_name: user_auth
container_support: mark@hng.tech
container_description: 'For user authentication'

push_metrics:
  lorona:
    your_unique_page: https://lorona.io/alexspecial # you can select any free page. It will automatically be created
    your_password: jcfRxQ7WXMFnES6TUizphW5DzhaTqNTiyckc2DgrdxYeHowo3PdLjeez3NFinydn # minimum 64 characters
    publish_interval: 1m

expose_metrics:
  prometheus_format:
    url: 0.0.0.0:5000
    format: 2
  json_format:
    url: 0.0.0.0:5001

uptime:
  - url: https://hng.tech
    status_check: https://hng.tech/status # Use this to test internal services
    expected_status: 200
    check_interval: 30s
    get_token_url: https://hng.tech/retrieve_token
  - url: https://google.com
    expected_status: 200
    search_for: 'photos'
    check_interval: 30s
    get_token_url: http://0.0.0.0:45246/retrieve_token
  - url: https://hng.agency

logs:
  - name: nginx-error
    filename: ./sample_logs/error.log
    alert_interval: hourly
    capture-line-if:
      - errorlevel=warning
      - condition: errorlevel=error
        alert: immediately

  - name: nginx-access
    filename: ./sample_logs/access.log
    capture-line-if:
      - statuscode = 404
      - condition: statuscode > 500 AND statuscode < 599
        alert: immediately
        repeat-alert: 5m

  - name: laravel
    filename: ./sample_logs/laravel.log
    capture-line-if:
      - errorlevel=warning

  - name: mysql-slow-query
    log_filename: ./sample_logs/mysql-slow.log
    capture-line-if:
      - querytime > 10s

system:
  drivespace:
    alert_level: 50GB
    repeat-alert: daily
    locations:
      - /var/www
      - /etc/nginx

  cpu:
    alert_level: 70%
    repeat-alert: daily

  ram:
    alert_level: 70%
    repeat-alert: daily

  process-monitor:
    repeat-alert: 1min
    processes:
      - docker

  heavy-load-watcher:
    minimum-time: 1m
    watch-cpu: yes
    watch-ram: yes
    watch-network: yes

backups-monitor:
  backup-folder: /var/db/backups
  backup-minimum-file-size: 30M
  remote-backup-format: s3
  remote-backup-location: s2
  check-backups: daily
  check-backups-time: 12am

alerts:
  handler: https://lorona.io/mailer
  emails:
    - mark@hng.tech
    - ikay@hng.tech

  slack:
    token: YC4YN8LRJ8RkEL
    key: YC4YN8LRJ8RkEL
    url: https://api.slack.com/notify
# Is process observation needed?
