
---
# Configuration file for Lorona - a very simple container monitoring solution

container_name: user_auth
container_support: mark@hng.tech
container_description: "For user authentication"

push_metrics:
  lorona:
    your_unique_page: https://lorona.io/alexspecial # you can select any free page. It will automatically be created
    your_password: jcfRxQ7WXMFnES6TUizphW5DzhaTqNTiyckc2DgrdxYeHowo3PdLjeez3NFinydn # minimum 64 characters
    publish_interval: 1m

expose_metrics:
  prometheus_format:
    url: 0.0.0.0:5000
    format: 2
  json_format:
    url: 0.0.0.0:5001

uptime:
  - url: https://hng.tech
    status_check: https://hng.tech/status                # Use this to test internal services
    expected_status: 200
    check_interval: 30s
    get_token_url: https://hng.tech/retrieve_token
  - url: https://google.com
    expected_status: 200
    search_for: "photos"
    check_interval: 30s
    get_token_url: http://0.0.0.0:45246/retrieve_token
  - url: https://hng.agency

nginx:
  error_log_filename: ./sample_logs/error.log
  errors:
    minimum_log_level: ERROR
    alert_level: 1
    alert_interval: hourly
  404:
    alert_level: 1
    alert_interval: hourly
  5xx:
    alert_level: 1
    alert_interval: 5mins

laravel:
  log_filename: log/laravel.log
  minimum_log_level: WARNING

mysql:
  log_filename: /var/www/mysql.log
  slow_query:
    slow_query_log: /var/www/slow.log
    alert_level: 10s

drivespace:
  alert_level: 50GB
  alert_interval: daily
  locations:
    - /var/www
    - /etc/nginx

cpu:
  alert_level: 70%
  alert_interval: daily

ram:
  alert_level: 70%
  alert_interval: daily

process-monitor:
  alert_interval: 1min
  processes:
    - docker

backups-monitor:
  backup-folder: /var/db/backups
  backup-minimum-file-size: 30M
  remote-backup-format: s3
  remote-backup-location: s2
  check-backups: daily
  check-backups-time: 12am

heavy-load-watcher:
  minimum-time: 1m
  watch-cpu: yes
  watch-ram: yes
  watch-network: yes


alerts:
  handler: https://lorona.io/mailer
  emails:
    - mark@hng.tech
    - ikay@hng.tech

  slack:
    token: YC4YN8LRJ8RkEL
    key: YC4YN8LRJ8RkEL
    url: https://api.slack.com/notify


# Is process observation needed?

...
