---
# Configuration file for Lorona - a very simple container monitoring solution

container-name: user_auth
container-support: mark@hng.tech
container-description: "For user authentication"

# This is an automatically created page that will aggregate all your containers together. You can easily
# view errors, logs, downtime, server ability, etc
push_metrics:
  lorona:
    your_unique_page: https://lorona.io/alexspecial # you can select any free page. It will automatically be created
    your-password: jcfRxQ7WXMFnES6TUizphW5DzhaTqNTiyckc2DgrdxYeHowo3PdLjeez3NFinydn # minimum 64 characters
    publish-interval: 1m

# If you need to graph the info collected here, it can be exposed in prometheus or json format
expose_metrics:
  prometheus_format:
    url: 0.0.0.0:5000
    format: 2
  json_format:
    url: 0.0.0.0:5001

# Monitor your endpoints. You can monitor from inside the micro-services or outside
uptime:
  - url: https://hng.tech
    status-check: https://hng.tech/status                # Use this to test internal services
    expected-status: 200
    check-interval: 30s
    get-token_url: https://hng.tech/retrieve_token
  - url: https://google.com
    expected-status: 200
    search-for: photos
    check-interval: 30s
    get-token-url: http://0.0.0.0:45246/retrieve_token

  - url: https://hng.agency

# Pull in the logs of your app, your web server and push them live. Set alerts for anytime something
# strange is seen in the logs.
logs:
  - name: "NGINX Error"
    filepath: ./sample_logs/error.log
    alert-interval: daily
    type: nginx-error-log2  # This has to correspond to a name in the log_formats file
    capture-line-if:
      - errorlevel = warning
      - errorlevel = error THEN alert immediately

  - name: nginx-access
    filepath: ./private_logs/access_100m.log
    type: nginx-access-log
    capture-line-if:
      - statuscode = 404
      - statuscode > 500 AND statuscode < 599 THEN alert immediately

  - name: laravel
    filepath: ./sample_logs/laravel.log
    capture-line-if:
      - errorlevel = warning

  - name: mysql-slow-query
    filepath: ./sample_logs/mysql-slow.log
    capture-line-if:
      - querytime > 10s

system:
  drivespace:
    alert_level: 50GB
    repeat-alert: daily
    locations:
      - /var/www
      - /etc/nginx

  cpu:
    alert_level: 70%
    repeat-alert: daily

  ram:
    alert_level: 70%
    repeat-alert: daily

  process-monitor:
    repeat-alert: 1min
    processes:
      - docker

  heavy-load-watcher:
    minimum-time: 1m
    watch-cpu: yes
    watch-ram: yes
    watch-network: yes

backups-monitor:
  backup-folder: /var/db/backups
  backup-minimum-file-size: 30M
  remote-backup-format: s3
  remote-backup-location: s2
  check-backups: daily
  check-backups-time: 12am

alerts:
  handler: https://mail.lorona.io/
  emails:
    - mark@hng.tech
    - simon@hng.tech

  slack:
    token: YC4YN8LRJ8RkEL
    key: YC4YN8LRJ8RkEL
    url: https://api.slack.com/notify
# Is process observation needed?
